import { demoScriptLimits } from "./demo-script.schema";

const CAPTURE_SCRIPT_GRACE_SECONDS = 30;
export const CAPTURE_SCRIPT_TIMEOUT_SECONDS =
  demoScriptLimits.maxTotalDurationSeconds + CAPTURE_SCRIPT_GRACE_SECONDS;
export const CAPTURE_SCRIPT_TIMEOUT_MS = CAPTURE_SCRIPT_TIMEOUT_SECONDS * 1_000;
export const CAPTURE_COMMAND_SHUTDOWN_GRACE_SECONDS = 10;
export const CAPTURE_COMMAND_TIMEOUT_MS =
  (CAPTURE_SCRIPT_TIMEOUT_SECONDS + CAPTURE_COMMAND_SHUTDOWN_GRACE_SECONDS) *
  1_000;
