import type {
  PreparationManifest,
  ValidationReport,
} from "../schemas/artifacts";
import type { PreparationWorkspaceDiff } from "./preparation-workspace-diff";

const dependencyConfigurationNames = new Set([
  ".npmrc",
  ".pnpmfile.cjs",
  ".yarnrc",
  ".yarnrc.yml",
  "bunfig.toml",
  "pnpm-workspace.yaml",
  "pnpm-workspace.yml",
  "pnpmfile.cjs",
]);

const lockfileNames = new Set([
  "bun.lock",
  "bun.lockb",
  "npm-shrinkwrap.json",
  "package-lock.json",
  "pnpm-lock.yaml",
  "yarn.lock",
]);

/** Summarizes file-content changes relevant to a dependency repair transaction. */
export function readDependencyRepairDelta(
  baseline: PreparationWorkspaceDiff,
  candidate: PreparationWorkspaceDiff,
) {
  const changedPaths = [
    ...new Set([
      ...Object.keys(baseline.changedFileSha256),
      ...Object.keys(candidate.changedFileSha256),
    ]),
  ].filter(
    (path) =>
      baseline.changedFileSha256[path] !== candidate.changedFileSha256[path],
  );
  return {
    changedPaths,
    dependencyInputsChanged: changedPaths.some(isDependencyRepairInputPath),
    onlyLockfiles:
      changedPaths.length > 0 &&
      changedPaths.every(isPackageManagerLockfilePath),
  };
}

/**
 * Verifies that Repo Preparation adapted the screened product rather than
 * replacing it with a newly authored demo application. During dependency
 * repair, executable source must remain unchanged from the accepted baseline.
 * Auth and integration edits must conditionally use a source-backed demo gate.
 */
type FidelityViolation = { hint: string; message: string };

const repairHints = {
  adaptOriginal:
    "Adapt the original application; do not create replacement servers, pages, styles, or commands.",
  dependencyScope:
    "Change only package manifests or recognized package-manager configuration during dependency repair.",
  envUsed:
    "Set demo environment through envUsed in the preparation manifest, not created env files.",
  gate: "Read the active MAKEADEMO_DEMO flag from envUsed directly or through one shared helper imported in the changed file, then conditionally select the demo path while preserving the normal behavior.",
  keepWorkspaces:
    "Keep the original workspace configuration; scope commands to the app instead.",
  lockfiles:
    "Never edit lockfiles; change package.json or package-manager configuration and the backend regenerates the lockfile.",
  preserveBehavior:
    "Re-add the removed lines on the non-demo branch; the gate must wrap original behavior, not delete it.",
  preserveUi:
    "Revert presentation changes; keep the original components, styles, and brand assets.",
  seam: "Move the change into an authentication, data, service, or configuration seam and gate it.",
  selfRequest:
    "Import the fixture or adapter directly instead of requesting your own listener.",
} as const;

export function validatePreparationFidelity(input: {
  dependencyRepair?: boolean;
  preparationManifest: PreparationManifest;
  repairBaseline?: PreparationWorkspaceDiff;
  repoSourceFiles: ReadonlyMap<string, string | undefined>;
  workspaceDiff: PreparationWorkspaceDiff;
}): ValidationReport {
  const violations: FidelityViolation[] = [];
  const repairPaths = readInvalidRepairPaths(input);
  const filePatches = parsePatchSections(input.workspaceDiff.patch);
  const demoGate = readDemoGateEvidence(
    input.preparationManifest,
    input.repoSourceFiles,
    input.workspaceDiff,
    filePatches,
  );
  for (const path of repairPaths) {
    violations.push(
      isPackageManagerLockfilePath(path)
        ? {
            hint: repairHints.lockfiles,
            message: `${path} was edited by the preparation repair agent; lockfiles must be generated by the backend package manager.`,
          }
        : {
            hint: repairHints.dependencyScope,
            message: `${path} was modified by dependency installation repair, which may change only package manifests or recognized package-manager configuration.`,
          },
    );
  }
  const createdPaths = input.workspaceDiff.changedPaths
    .map(toRepoRelativePath)
    .filter((path) => !input.repoSourceFiles.has(path));
  const modifiedOriginalPaths = input.workspaceDiff.changedPaths
    .map(toRepoRelativePath)
    .filter((path) => input.repoSourceFiles.has(path));

  for (const path of modifiedOriginalPaths) {
    if (repairPaths.has(path)) continue;
    const patch = filePatches.get(path) ?? "";
    if (addsServerSelfRequest(path, patch, input.preparationManifest.baseUrl)) {
      violations.push({
        hint: repairHints.selfRequest,
        message: `${path} calls back through its own listener from server-side code, which can recursively stall rendering. Use the fixture or adapter directly instead.`,
      });
      continue;
    }
    if (isFrameworkConfigPath(path)) continue;
    const addsPresentation = addsProductPresentation(patch);
    const demoSeam = isDemoSeamPath(path);
    const authenticationAdaptation = isAuthenticationAdaptation(path, patch);
    const integrationAdaptation = isIntegrationAdaptation(path, patch);
    if (authenticationAdaptation || integrationAdaptation) {
      if (addsPresentation) {
        violations.push({
          hint: repairHints.preserveUi,
          message: `${path} modifies original product UI, styling, or brand assets instead of preserving them.`,
        });
        continue;
      }
      const kind = authenticationAdaptation ? "authentication" : "integration";
      const violation = readDemoAdaptationViolation(
        demoGate,
        path,
        patch,
        kind,
        input.repoSourceFiles.get(path) ?? "",
      );
      if (violation !== undefined) {
        violations.push({ hint: repairHints.gate, message: violation });
        continue;
      }
      const unpreserved = readUnpreservedRemovedLine(patch);
      if (unpreserved !== undefined) {
        violations.push({
          hint: repairHints.preserveBehavior,
          message: `${path} removes original ${kind} behavior (\`${unpreserved}\`) instead of preserving it behind the demo gate.`,
        });
      }
      continue;
    }
    if (demoSeam && !addsPresentation) {
      continue;
    }
    if (isProductPresentationPath(path)) {
      if (!onlyLocalizesExternalAssets(patch)) {
        violations.push({
          hint: repairHints.preserveUi,
          message: `${path} modifies original product UI, styling, or brand assets instead of preserving them.`,
        });
      }
    } else if (isExecutableSourcePath(path) && !demoSeam) {
      violations.push({
        hint: repairHints.seam,
        message: `${path} modifies original feature logic outside an authentication, data, service, or configuration seam.`,
      });
    }
  }

  const resolvedStartCommands = readResolvedStartCommands(
    input.preparationManifest.startCommandUsed,
    input.repoSourceFiles,
    filePatches.get("package.json") ?? "",
  );
  for (const path of createdPaths) {
    if (repairPaths.has(path)) continue;
    const patch = filePatches.get(path) ?? "";
    if (addsServerSelfRequest(path, patch, input.preparationManifest.baseUrl)) {
      violations.push({
        hint: repairHints.selfRequest,
        message: `${path} calls back through its own listener from server-side code, which can recursively stall rendering. Use the fixture or adapter directly instead.`,
      });
      continue;
    }
    if (isDotenvPath(path) && containsAuthenticationTerms(patch)) {
      violations.push({
        hint: repairHints.envUsed,
        message: `${path} changes authentication behavior through a created environment file; demo environment belongs in envUsed with a gated adaptation.`,
      });
    }
    if (
      isProductPresentationPath(path) &&
      !isVendoredAssetPath(path) &&
      (!isDemoSeamPath(path) || addsProductPresentation(patch))
    ) {
      violations.push({
        hint: repairHints.adaptOriginal,
        message: `${path} creates replacement product UI instead of adapting the original application.`,
      });
    }
    if (isStandaloneReplacementRuntime(patch)) {
      violations.push({
        hint: repairHints.adaptOriginal,
        message: `${path} creates a standalone server with replacement product markup or styling.`,
      });
    }
    if (
      resolvedStartCommands.some((command) =>
        commandReferencesPath(command, path),
      )
    ) {
      violations.push({
        hint: repairHints.adaptOriginal,
        message: `The prepared start command launches newly created application entrypoint ${path}.`,
      });
    }
  }

  const packagePatch = filePatches.get("package.json") ?? "";
  if (/^-.*["']workspaces["']/m.test(packagePatch)) {
    violations.push({
      hint: repairHints.keepWorkspaces,
      message:
        "package.json removes the original workspace configuration instead of adapting the original app.",
    });
  }
  for (const path of createdPaths) {
    if (!isDemoSeamPath(path) && addedPatchText(packagePatch).includes(path)) {
      violations.push({
        hint: repairHints.adaptOriginal,
        message: `package.json redirects an application command to newly created file ${path}.`,
      });
    }
  }

  return createFidelityReport(violations);
}

function readInvalidRepairPaths(input: {
  dependencyRepair?: boolean;
  repairBaseline?: PreparationWorkspaceDiff;
  workspaceDiff: PreparationWorkspaceDiff;
}): Set<string> {
  const baseline = input.repairBaseline;
  if (baseline === undefined) {
    return new Set();
  }
  return new Set(
    readDependencyRepairDelta(
      baseline,
      input.workspaceDiff,
    ).changedPaths.filter(
      (path) =>
        isPackageManagerLockfilePath(path) ||
        (input.dependencyRepair === true && !isDependencyRepairInputPath(path)),
    ),
  );
}

function isDependencyRepairInputPath(path: string): boolean {
  const name = path.split("/").at(-1) ?? path;
  return name === "package.json" || dependencyConfigurationNames.has(name);
}

function isPackageManagerLockfilePath(path: string): boolean {
  return lockfileNames.has(path.split("/").at(-1) ?? path);
}

function createFidelityReport(
  violations: FidelityViolation[],
): ValidationReport {
  const passed = violations.length === 0;
  return {
    artifactReferences: [
      "/workspace/.makeademo/preparation-workspace-diff.json",
      "/workspace/.makeademo/preparation-manifest.json",
    ],
    blockedNetworkAttempts: [],
    browserObservations: [],
    consoleErrors: [],
    ...(passed ? {} : { failureClassification: "product fidelity violation" }),
    logsSummary: passed
      ? "Prepared runtime preserves the screened product application."
      : `Prepared runtime does not preserve the screened product: ${violations
          .map((violation) => violation.message)
          .join(" ")}`,
    networkAttempts: [],
    pageErrors: [],
    retryCount: 0,
    screenshots: [],
    stage: "preparation-fidelity",
    status: passed ? "passed" : "failed",
    stderrExcerpts: [],
    stdoutExcerpts: [],
    suggestedRepairHints: [
      ...new Set(violations.map((violation) => violation.hint)),
    ],
  };
}

function isStandaloneReplacementRuntime(patch: string) {
  const additions = addedPatchText(patch);
  return (
    /\b(?:Bun\.serve|createServer|serve)\s*\(/.test(additions) &&
    /(?:<!doctype\s+html|<html\b|<style\b|style\s*=)/i.test(additions)
  );
}

function addsServerSelfRequest(path: string, patch: string, baseUrl: string) {
  if (!isServerExecutionPath(path)) return false;
  const additions = addedPatchText(patch);
  if (
    !/\b(?:axios|fetch|got|httpBatchLink|httpLink|request|superagent|urllib)\b/i.test(
      additions,
    )
  ) {
    return false;
  }
  const url = new URL(baseUrl);
  const port = url.port || (url.protocol === "https:" ? "443" : "80");
  const ownListenerPattern = `https?:\\/\\/(?:127\\.0\\.0\\.1|0\\.0\\.0\\.0|localhost|\\[?::1\\]?):${escapeRegExp(port)}(?:[/\\s'\"\`]|$)`;
  return new RegExp(ownListenerPattern, "i").test(additions);
}

function isServerExecutionPath(path: string) {
  return /(?:^|\/)(?:api|backend|rpc|server|trpc)(?:\/|$)|(?:^|[._-])server\.[^/]+$/i.test(
    path,
  );
}

function addsProductPresentation(patch: string) {
  const additions = changedPatchLines(patch, "+").join("\n");
  return (
    /<!doctype\s+html|<(?:a|article|aside|body|button|canvas|dialog|div|footer|form|h[1-6]|header|html|img|input|label|li|main|nav|ol|p|section|select|span|style|svg|table|textarea|ul|video)\b/i.test(
      additions,
    ) ||
    /(?:return\s*\(?|=>\s*\(?)\s*<\/?[A-Z]/.test(additions) ||
    /^\s*<\/?[A-Z][A-Za-z0-9.]*\b[^>]*>/m.test(additions) ||
    /\b(?:className|dangerouslySetInnerHTML|style)\s*=/.test(additions)
  );
}

function onlyLocalizesExternalAssets(patch: string) {
  const removed = changedPatchLines(patch, "-");
  const added = changedPatchLines(patch, "+");
  return (
    removed.length > 0 &&
    removed.length === added.length &&
    removed.every((before, index) => {
      const after = added[index] ?? "";
      const external =
        /(["'])((?:https?:)?\/\/[^"']+)\1/.exec(before)?.[2] ??
        /url\(\s*((?:https?:)?\/\/[^)\s"']+)\s*\)/i.exec(before)?.[1];
      const local =
        /(["'])((?:\.?\.\/|\/)[^"']+\.[a-z0-9]+(?:[?#][^"']*)?)\1/i.exec(
          after,
        )?.[2] ??
        /url\(\s*((?:\.?\.\/|\/)[^)\s"']+\.[a-z0-9]+)\s*\)/i.exec(after)?.[1];
      return (
        external !== undefined &&
        local !== undefined &&
        before.replace(external, "__ASSET__") ===
          after.replace(local, "__ASSET__")
      );
    })
  );
}

function changedPatchLines(patch: string, prefix: "+" | "-") {
  const headerPrefix = prefix.repeat(3);
  return patch
    .split("\n")
    .filter((line) => line.startsWith(prefix) && !line.startsWith(headerPrefix))
    .map((line) => line.slice(1));
}

function isProductPresentationPath(path: string) {
  return (
    /\.(?:css|html|jsx|less|png|jpe?g|scss|svg|svelte|tsx|vue|webp)$/i.test(
      path,
    ) ||
    /(?:^|\/)(?:app|components|pages|routes|screens|views)(?:\/|$)/i.test(path)
  );
}

function isDemoSeamPath(path: string) {
  return /(?:^|[./_-])(?:adapters?|api|auth|caches?|clients?|configs?|data|databases?|db|env|fixtures?|gateways?|graphql|integrations?|middleware|mocks?|providers?|proxy|repositor(?:y|ies)|rpc|seeds?|services?|sessions?|stores?|trpc)(?:[./_-]|$)/i.test(
    path,
  );
}

interface DemoGateEvidence {
  flags: string[];
  identifiers: string[];
}

function readDemoGateEvidence(
  preparationManifest: PreparationManifest,
  repoSourceFiles: ReadonlyMap<string, string | undefined>,
  workspaceDiff: PreparationWorkspaceDiff,
  filePatches: ReadonlyMap<string, string>,
): DemoGateEvidence {
  const configuredFlags = Object.entries(preparationManifest.envUsed)
    .filter(
      ([key, value]) =>
        /(?:^|_)MAKEADEMO_DEMO$/i.test(key) && /^(?:1|true)$/i.test(value),
    )
    .map(([key]) => key);
  if (configuredFlags.length === 0) {
    return { flags: [], identifiers: [] };
  }
  const sources = [
    ...[...repoSourceFiles]
      .filter(
        ([path, source]) =>
          source !== undefined && isExecutableSourcePath(path),
      )
      .map(([, source]) => source ?? ""),
    ...workspaceDiff.changedPaths
      .map(toRepoRelativePath)
      .filter(isExecutableSourcePath)
      .map((path) => addedPatchText(filePatches.get(path) ?? "")),
  ];
  const flags = configuredFlags.filter((flag) =>
    sources.some((source) => readsDemoFlag(source, flag)),
  );
  return {
    flags,
    identifiers: [
      ...new Set(
        sources.flatMap((source) => readDemoGateIdentifiers(source, flags)),
      ),
    ],
  };
}

function readDemoAdaptationViolation(
  demoGate: DemoGateEvidence,
  path: string,
  patch: string,
  kind: "authentication" | "integration",
  originalSource: string,
): string | undefined {
  if (demoGate.flags.length === 0) {
    return missingDemoGateViolation(path, kind);
  }
  if (!hasConditionalDemoGate(patch, demoGate, originalSource)) {
    return `${path} does not conditionally use the repository's active MakeADemo demo gate for the ${kind} adaptation.`;
  }
  return undefined;
}

/**
 * Returns the first removed line whose content is not recoverable from the
 * additions. A gated adaptation must wrap original behavior, not delete it:
 * every removed non-blank line must survive verbatim or token-by-token (the
 * token fallback tolerates gate wrapping such as inline ternaries).
 */
function readUnpreservedRemovedLine(patch: string): string | undefined {
  const additions = addedPatchText(patch);
  for (const removed of changedPatchLines(patch, "-")) {
    const line = removed.trim();
    if (line.length < 3 || /^[{}()[\]<>/*,;`'"\\|&-]*$/.test(line)) continue;
    if (additions.includes(line)) continue;
    const tokens = line.match(/[A-Za-z0-9_$"'`./-]{3,}/g) ?? [];
    if (tokens.length === 0) continue;
    if (tokens.every((token) => additions.includes(token))) continue;
    return line.length > 80 ? `${line.slice(0, 80)}…` : line;
  }
  return undefined;
}

function readsDemoFlag(source: string, flag: string) {
  return new RegExp(
    `(?:\\$\\{?|(?:config|env(?:ironment)?|getenv|settings)\\b[\\s\\S]{0,80})${escapeRegExp(flag)}(?![A-Za-z0-9_])`,
    "i",
  ).test(source);
}

function isAuthenticationAdaptation(path: string, patch: string) {
  return (
    isExecutableSourcePath(path) &&
    (containsAuthenticationTerms(patch) ||
      /(?:^|[./_-])(?:auth|identity|login|oauth|principal|session)(?:[./_-]|$)/i.test(
        path,
      ))
  );
}

function isIntegrationAdaptation(path: string, patch: string) {
  return (
    isExecutableSourcePath(path) &&
    (isDemoSeamPath(path) || containsIntegrationTerms(patch))
  );
}

function containsAuthenticationTerms(source: string) {
  return /\b(?:auth(?:entication|orization)?|claims?|credentials?|current\s+users?|identity|login|logout|oauth|principal|redirect|sessions?|sign\s+(?:in|out))\b/i.test(
    normalizedWords(source),
  );
}

function containsIntegrationTerms(source: string) {
  return /\b(?:api|caches?|clients?|data\s+sources?|databases?|fixtures?|gateways?|graphql|mocks?|repositor(?:y|ies)|rpc|services?)\b/i.test(
    normalizedWords(source),
  );
}

function normalizedWords(source: string) {
  return source.replace(/([a-z0-9])([A-Z])/g, "$1 $2").replace(/[_$-]+/g, " ");
}

function missingDemoGateViolation(
  path: string,
  kind: "authentication" | "integration",
) {
  return `${path} changes ${kind} behavior without an active MakeADemo demo flag recorded in envUsed.`;
}

function hasConditionalDemoGate(
  patch: string,
  demoGate: DemoGateEvidence,
  originalSource: string,
) {
  const additions = stripComments(addedPatchText(patch));
  const fileScope = `${stripComments(originalSource)}\n${additions}`;
  const tokens = [
    ...demoGate.flags.filter((flag) => readsDemoFlag(additions, flag)),
    ...demoGate.identifiers.filter((identifier) =>
      isBoundInFile(fileScope, identifier),
    ),
  ];
  return tokens.some((token) => isConditionalUse(additions, token));
}

function stripComments(source: string) {
  return source
    .replace(/\/\*[\s\S]*?\*\//g, " ")
    .replace(/(?:^|(?<=\s))(?:\/\/|#).*$/gm, " ");
}

/** A gate identifier only counts inside a file that imports or declares it. */
function isBoundInFile(source: string, identifier: string) {
  const name = escapeRegExp(identifier);
  return (
    new RegExp(`\\bimport\\b[^;\\n]*[{,\\s]${name}\\s*[},\\s]`).test(source) ||
    new RegExp(`\\b(?:const|let|var|final|bool|boolean)\\s+${name}\\b`).test(
      source,
    ) ||
    new RegExp(`\\b(?:def|fn|func|function)\\s+${name}\\s*\\(`).test(source) ||
    new RegExp(`\\bfrom\\b[^\\n]*\\bimport\\b[^\\n]*\\b${name}\\b`).test(source)
  );
}

function readDemoGateIdentifiers(source: string, flags: string[]) {
  const identifiers = new Set<string>();
  for (const flag of flags) {
    const name = escapeRegExp(flag);
    const patterns = [
      new RegExp(
        `\\b(?:const|final|let|var|bool|boolean)\\s+([A-Za-z_$][\\w$]*)\\s*[:=][^;\\n]*(?<![A-Za-z0-9_])${name}(?![A-Za-z0-9_])`,
        "g",
      ),
      new RegExp(
        `\\b(?:def|fn|func|function)\\s+([A-Za-z_$][\\w$]*)\\s*\\([^)]*\\)[^]{0,160}?(?<![A-Za-z0-9_])${name}(?![A-Za-z0-9_])`,
        "g",
      ),
    ];
    for (const pattern of patterns) {
      for (const match of source.matchAll(pattern)) {
        if (match[1] !== undefined) identifiers.add(match[1]);
      }
    }
  }
  return [...identifiers];
}

function isConditionalUse(source: string, token: string) {
  const conditional = "(?:\\b(?:if|unless)\\b|\\?|&&|\\|\\|)";
  const reference = `(?:^|[^A-Za-z0-9_$])${escapeRegExp(token)}(?![A-Za-z0-9_$])`;
  return new RegExp(
    `(?:${conditional}[^;]{0,160}${reference}|${reference}[^;]{0,160}${conditional})`,
    "m",
  ).test(source);
}

function escapeRegExp(value: string) {
  return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

function isExecutableSourcePath(path: string) {
  return /\.(?:cjs|cs|go|java|js|jsx|mjs|mts|php|py|rb|rs|sh|svelte|ts|tsx|vue)$/i.test(
    path,
  );
}

function isVendoredAssetPath(path: string) {
  return (
    /(?:^|\/)(?:assets|fonts|images|public|static|vendor)(?:\/|$)/i.test(
      path,
    ) &&
    /\.(?:avif|eot|gif|ico|jpe?g|mp3|mp4|ogg|otf|png|svg|ttf|wav|webm|webp|woff2?)$/i.test(
      path,
    )
  );
}

function commandReferencesPath(command: string, path: string) {
  return command.split(/\s+/).some((token) => token === path);
}

/**
 * Resolves a package-manager start command one level through the script table
 * so a created entrypoint cannot hide behind `npm run <script>`. Reads both
 * the original package.json and script lines added by the preparation patch.
 */
function readResolvedStartCommands(
  startCommandUsed: string,
  repoSourceFiles: ReadonlyMap<string, string | undefined>,
  packagePatch: string,
): string[] {
  const commands = [startCommandUsed];
  const scriptName =
    /^\s*(?:corepack\s+)?(?:bun|npm|pnpm|yarn)\s+(?:run\s+)?([\w:.-]+)/.exec(
      startCommandUsed,
    )?.[1];
  if (scriptName === undefined) return commands;
  const sources = [
    repoSourceFiles.get("package.json") ?? "",
    addedPatchText(packagePatch),
  ];
  for (const source of sources) {
    const script = new RegExp(
      `"${escapeRegExp(scriptName)}"\\s*:\\s*"([^"]+)"`,
    ).exec(source)?.[1];
    if (script !== undefined) commands.push(script);
  }
  return commands;
}

function isDotenvPath(path: string) {
  const name = path.split("/").at(-1) ?? path;
  return /^\.env(?:\..+)?$/.test(name) && name !== ".env.example";
}

function addedPatchText(patch: string) {
  return patch
    .split("\n")
    .filter((line) => line.startsWith("+") && !line.startsWith("+++"))
    .map((line) => line.slice(1))
    .join("\n");
}

/**
 * Splits a unified diff into per-file sections in one pass. Section headers
 * match only at line starts, so header-shaped text inside added or removed
 * content cannot open a section. Renamed files register under both paths.
 */
function parsePatchSections(patch: string): Map<string, string> {
  const sections = new Map<string, string>();
  const lines = patch.split("\n");
  let start = -1;
  let paths: string[] = [];
  const flush = (end: number) => {
    if (start === -1) return;
    const section = lines.slice(start, end).join("\n");
    for (const path of paths) {
      const existing = sections.get(path);
      sections.set(
        path,
        existing === undefined ? section : `${existing}\n${section}`,
      );
    }
  };
  for (const [index, line] of lines.entries()) {
    const header =
      /^diff --git (?:"a\/(.+?)"|a\/(.+?)) (?:"b\/(.+?)"|b\/(.+))$/.exec(line);
    if (header === null) continue;
    flush(index);
    start = index;
    paths = [
      ...new Set(
        [header[1] ?? header[2], header[3] ?? header[4]].filter(
          (path): path is string => path !== undefined,
        ),
      ),
    ];
  }
  flush(lines.length);
  return sections;
}

function isFrameworkConfigPath(path: string) {
  const name = path.split("/").at(-1) ?? path;
  return (
    /^[^/]*\.config\.[cm]?[jt]sx?$/i.test(name) ||
    /^tsconfig[^/]*\.json$/i.test(name) ||
    name === ".env.example"
  );
}

function toRepoRelativePath(path: string) {
  return path.replace(/^\/workspace\/repo\//, "").replace(/^\.\//, "");
}
